version: "3.3"
services:
  kapacitor:
    image: kapacitor:1.5-alpine
    volumes:
      - /mnt/data/kapacitor:/var/lib/kapacitor
      - /root/configs/kapacitor/ticks:/home/kapacitor
      - /root/configs/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    labels:
      - "traefik.backend=kapacitorbackend"
      - "traefik.docker.network=root_default"
      - "traefik.frontend.rule=Host:kapacitor.tinyangrykitten.dev"
      - "traefik.enable=true"
      - "traefik.port=9092"
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--entrypoints.mqtt.address=:1883"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/configs/traefik/traefik.toml:/traefik.toml
      - /root/configs/traefik/acme.json:/acme.json
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - /root/configs/telegraf:/etc/telegraf
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - target: 1883
        published: 1883
      - target: 9001
        published: 9001
    labels:
      - "traefik.backend=mosquittobackend"
      - "traefik.docker.network=root_default"
      - "traefik.frontend.rule=Host:mqtts.tinyangrykitten.dev"
      - "traefik.enable=true"
      - "traefik.port=9001"

      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.tcpr_mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.tcpr_mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tcpr_mqtt.service=mqtt"
    volumes:
      - /root/configs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /root/configs/mosquitto/logs:/mosquitto/config/logs
  chronograf:
    image: chronograf:1.8
    restart: always
    volumes:
      - /mnt/data/chronograf:/var/lib/chronograf
    labels:
      - "traefik.backend=chronografbackend"
      - "traefik.docker.network=root_default"
      - "traefik.frontend.rule=Host:chronograf.tinyangrykitten.dev"
      - "traefik.enable=true"
      - "traefik.port=8888"
  influx:
    image: influxdb
    restart: always
    ports:
      - target: 8086
        published: 8086
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
    volumes:
      - /mnt/data/influxdb:/var/lib/influxdb
      - /root/configs/influxdb:/etc/influxdb
